services:
  frontend:
    build: ./zaliczenie_front
    ports:
    #bindujemy port exposowany z dockerfila frontendu do portu hosta 3000
      - "3000:80"
    depends_on:
          - backend
      # backend:
        # condition: service_healthy
    restart: on-failure
    
  backend:
    build: ./zaliczenie_back_db
    ports: # ogólnie powinno być 'expose' -exposujemy w sieci dokerowej, ale nie dla hosta (nie dostaniemy sie z przegladarki na endpoint z backendu, tylko przez front)
      - "8080:8080"

    restart: on-failure
    # healthcheck: 
    #   test: ["CMD","curl 127.0.0.1:8080 || exit 1"]
    #   interval: 10s # uruchamiamy test co 10s 
    #   retries: 100  # 100 sprawdzen czy backend juz dziala, jak nie to front sie nie postawi
    #   timeout: 10s # jesli sam test zajmie wiecej niz 10 sekund to ta proba uznawana jest za faila
    #   start_period: 240s # probujemy postawic po 240s (healthchecki sie odbywaja, --- jesli bedzie fail to nie liczy sie do retries, a jesli
    #   # bedzie healthy to juz postawi front)
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: music_db
    
    ports:
      - "3306:3306"



